[2024-03-11 04:35:05,856] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting_project492.merge_data 2024-03-11T04:34:56.277255+00:00 [queued]>
[2024-03-11 04:35:05,866] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting_project492.merge_data 2024-03-11T04:34:56.277255+00:00 [queued]>
[2024-03-11 04:35:05,867] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2024-03-11 04:35:05,867] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2024-03-11 04:35:05,867] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2024-03-11 04:35:05,882] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): merge_data> on 2024-03-11T04:34:56.277255+00:00
[2024-03-11 04:35:05,886] {standard_task_runner.py:52} INFO - Started process 5274 to run task
[2024-03-11 04:35:05,889] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'meeting_project492', 'merge_data', '2024-03-11T04:34:56.277255+00:00', '--job-id', '638', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp29enbgwq', '--error-file', '/tmp/tmpxz1xs1al']
[2024-03-11 04:35:05,891] {standard_task_runner.py:77} INFO - Job 638: Subtask merge_data
[2024-03-11 04:35:05,928] {logging_mixin.py:109} INFO - Running <TaskInstance: meeting_project492.merge_data 2024-03-11T04:34:56.277255+00:00 [running]> on host 5fe9ddfe21b9
[2024-03-11 04:35:05,980] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=meeting_project492
AIRFLOW_CTX_TASK_ID=merge_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-11T04:34:56.277255+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-11T04:34:56.277255+00:00
[2024-03-11 04:35:06,023] {python.py:151} INFO - Done. Returned value was: None
[2024-03-11 04:35:06,032] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=meeting_project492, task_id=merge_data, execution_date=20240311T043456, start_date=20240311T043505, end_date=20240311T043506
[2024-03-11 04:35:06,061] {local_task_job.py:151} INFO - Task exited with return code 0
[2024-03-11 04:35:06,080] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
