[2024-03-11 04:15:18,101] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting_project492.merge_data 2024-03-11T04:15:13.309201+00:00 [queued]>
[2024-03-11 04:15:18,115] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting_project492.merge_data 2024-03-11T04:15:13.309201+00:00 [queued]>
[2024-03-11 04:15:18,115] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2024-03-11 04:15:18,116] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2024-03-11 04:15:18,116] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2024-03-11 04:15:18,126] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): merge_data> on 2024-03-11T04:15:13.309201+00:00
[2024-03-11 04:15:18,131] {standard_task_runner.py:52} INFO - Started process 1493 to run task
[2024-03-11 04:15:18,133] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'meeting_project492', 'merge_data', '2024-03-11T04:15:13.309201+00:00', '--job-id', '578', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpu8f24x8i', '--error-file', '/tmp/tmpydq96gtt']
[2024-03-11 04:15:18,135] {standard_task_runner.py:77} INFO - Job 578: Subtask merge_data
[2024-03-11 04:15:18,172] {logging_mixin.py:109} INFO - Running <TaskInstance: meeting_project492.merge_data 2024-03-11T04:15:13.309201+00:00 [running]> on host 76207e23fd35
[2024-03-11 04:15:18,224] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=meeting_project492
AIRFLOW_CTX_TASK_ID=merge_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-11T04:15:13.309201+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-11T04:15:13.309201+00:00
[2024-03-11 04:15:18,264] {python.py:151} INFO - Done. Returned value was: None
[2024-03-11 04:15:18,273] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=meeting_project492, task_id=merge_data, execution_date=20240311T041513, start_date=20240311T041518, end_date=20240311T041518
[2024-03-11 04:15:18,306] {local_task_job.py:151} INFO - Task exited with return code 0
[2024-03-11 04:15:18,327] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
