[2024-03-11 04:30:26,195] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting_project492.merge_data 2024-03-11T04:30:18.774911+00:00 [queued]>
[2024-03-11 04:30:26,205] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting_project492.merge_data 2024-03-11T04:30:18.774911+00:00 [queued]>
[2024-03-11 04:30:26,206] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2024-03-11 04:30:26,206] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2024-03-11 04:30:26,206] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2024-03-11 04:30:26,218] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): merge_data> on 2024-03-11T04:30:18.774911+00:00
[2024-03-11 04:30:26,224] {standard_task_runner.py:52} INFO - Started process 2980 to run task
[2024-03-11 04:30:26,226] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'meeting_project492', 'merge_data', '2024-03-11T04:30:18.774911+00:00', '--job-id', '619', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpxb2v2cd0', '--error-file', '/tmp/tmpuopx0tnf']
[2024-03-11 04:30:26,229] {standard_task_runner.py:77} INFO - Job 619: Subtask merge_data
[2024-03-11 04:30:26,270] {logging_mixin.py:109} INFO - Running <TaskInstance: meeting_project492.merge_data 2024-03-11T04:30:18.774911+00:00 [running]> on host 5fe9ddfe21b9
[2024-03-11 04:30:26,321] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=meeting_project492
AIRFLOW_CTX_TASK_ID=merge_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-11T04:30:18.774911+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-11T04:30:18.774911+00:00
[2024-03-11 04:30:26,361] {python.py:151} INFO - Done. Returned value was: None
[2024-03-11 04:30:26,371] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=meeting_project492, task_id=merge_data, execution_date=20240311T043018, start_date=20240311T043026, end_date=20240311T043026
[2024-03-11 04:30:26,399] {local_task_job.py:151} INFO - Task exited with return code 0
[2024-03-11 04:30:26,418] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
