[2024-03-01 14:58:09,578] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting.merge_data 2024-03-01T14:58:04.514046+00:00 [queued]>
[2024-03-01 14:58:09,593] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting.merge_data 2024-03-01T14:58:04.514046+00:00 [queued]>
[2024-03-01 14:58:09,593] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 14:58:09,593] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2024-03-01 14:58:09,593] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 14:58:09,602] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): merge_data> on 2024-03-01T14:58:04.514046+00:00
[2024-03-01 14:58:09,606] {standard_task_runner.py:52} INFO - Started process 3399 to run task
[2024-03-01 14:58:09,609] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'meeting', 'merge_data', '2024-03-01T14:58:04.514046+00:00', '--job-id', '195', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpd41j46o1', '--error-file', '/tmp/tmp55k_xrno']
[2024-03-01 14:58:09,611] {standard_task_runner.py:77} INFO - Job 195: Subtask merge_data
[2024-03-01 14:58:09,646] {logging_mixin.py:109} INFO - Running <TaskInstance: meeting.merge_data 2024-03-01T14:58:04.514046+00:00 [running]> on host b272d77a87bd
[2024-03-01 14:58:09,692] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=meeting
AIRFLOW_CTX_TASK_ID=merge_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-01T14:58:04.514046+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-01T14:58:04.514046+00:00
[2024-03-01 14:58:09,715] {python.py:151} INFO - Done. Returned value was: None
[2024-03-01 14:58:09,725] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=meeting, task_id=merge_data, execution_date=20240301T145804, start_date=20240301T145809, end_date=20240301T145809
[2024-03-01 14:58:09,781] {local_task_job.py:151} INFO - Task exited with return code 0
[2024-03-01 14:58:09,802] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
