[2023-12-27 14:16:32,423] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting.merge_data 2023-12-27T13:00:00+00:00 [queued]>
[2023-12-27 14:16:32,436] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting.merge_data 2023-12-27T13:00:00+00:00 [queued]>
[2023-12-27 14:16:32,436] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 14:16:32,436] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2023-12-27 14:16:32,436] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2023-12-27 14:16:32,443] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): merge_data> on 2023-12-27T13:00:00+00:00
[2023-12-27 14:16:32,448] {standard_task_runner.py:52} INFO - Started process 790 to run task
[2023-12-27 14:16:32,450] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'meeting', 'merge_data', '2023-12-27T13:00:00+00:00', '--job-id', '112', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp1ce07ozv', '--error-file', '/tmp/tmpxjf333c8']
[2023-12-27 14:16:32,452] {standard_task_runner.py:77} INFO - Job 112: Subtask merge_data
[2023-12-27 14:16:32,487] {logging_mixin.py:109} INFO - Running <TaskInstance: meeting.merge_data 2023-12-27T13:00:00+00:00 [running]> on host 6fcf1040ed70
[2023-12-27 14:16:32,534] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=meeting
AIRFLOW_CTX_TASK_ID=merge_data
AIRFLOW_CTX_EXECUTION_DATE=2023-12-27T13:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-27T13:00:00+00:00
[2023-12-27 14:16:32,554] {python.py:151} INFO - Done. Returned value was: None
[2023-12-27 14:16:32,563] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=meeting, task_id=merge_data, execution_date=20231227T130000, start_date=20231227T141632, end_date=20231227T141632
[2023-12-27 14:16:32,583] {local_task_job.py:151} INFO - Task exited with return code 0
[2023-12-27 14:16:32,604] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
