[2024-03-09 03:03:34,843] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting_project492.merge_data 2024-03-09T03:03:28.987377+00:00 [queued]>
[2024-03-09 03:03:34,854] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: meeting_project492.merge_data 2024-03-09T03:03:28.987377+00:00 [queued]>
[2024-03-09 03:03:34,854] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2024-03-09 03:03:34,854] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2024-03-09 03:03:34,854] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2024-03-09 03:03:34,866] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): merge_data> on 2024-03-09T03:03:28.987377+00:00
[2024-03-09 03:03:34,871] {standard_task_runner.py:52} INFO - Started process 3771 to run task
[2024-03-09 03:03:34,873] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'meeting_project492', 'merge_data', '2024-03-09T03:03:28.987377+00:00', '--job-id', '377', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpjuvbhsg_', '--error-file', '/tmp/tmpf9zuo3ch']
[2024-03-09 03:03:34,876] {standard_task_runner.py:77} INFO - Job 377: Subtask merge_data
[2024-03-09 03:03:34,911] {logging_mixin.py:109} INFO - Running <TaskInstance: meeting_project492.merge_data 2024-03-09T03:03:28.987377+00:00 [running]> on host 62b9685fb4d1
[2024-03-09 03:03:34,957] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=meeting_project492
AIRFLOW_CTX_TASK_ID=merge_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-09T03:03:28.987377+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-09T03:03:28.987377+00:00
[2024-03-09 03:03:34,989] {python.py:151} INFO - Done. Returned value was: None
[2024-03-09 03:03:34,997] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=meeting_project492, task_id=merge_data, execution_date=20240309T030328, start_date=20240309T030334, end_date=20240309T030334
[2024-03-09 03:03:35,046] {local_task_job.py:151} INFO - Task exited with return code 0
[2024-03-09 03:03:35,067] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
